(define Macro1
   (lambda ( )
    (edit:clear-selection)
(edit:add-selection (entity 1))
(property:apply-material (entity 1) "SCHOTT" "BK7" (gvector 0 0 0))
(edit:clear-selection)
(edit:add-selection (entity 2))
(property:apply-surface (entity 2) (list "Perfect Absorber" "Default")
  (gvector 0 0 0) (gvector 0 0 0)
  (position 0 0 0) (gvector 0 0 0) #t)
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 0 (entity 3)))
(property:apply-flux-surface-source (tools:face-in-body 0 (entity 3)) 100 1000 2 #f)
))