(define Macro1
   (lambda ( )
    (analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 1000 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
(analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 4 #f 1000 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
(analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 1000 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
(analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 10000 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
(analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 100 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
(analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 1000 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
(analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 500 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
(analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 100 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
(analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 500 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #t)
(analysis:candela-rect-distribution-angular-width 180)
))

(define Macro1
   (lambda ( )
    (analysis:candela-normal (gvector 0 -1 0))
(analysis:candela-up (gvector -1 0 0))
(analysis:candela-ray-type "missed")
(analysis:candela-symmetry "none")
(analysis:candela-polar-angular-width 90)
(analysis:candela-polar-color 0)
(analysis:candela-polar-contour #f)
(analysis:candela-polar-smooth #f 90)
(analysis:candela-polar-log-plot #f)
(analysis:candela-polar-max #f 0)
(analysis:candela-polar-min #f 0)
(analysis:candela-polar-levels -1)
(analysis:candela-rectangular-height-width 10 10)
(analysis:candela-rectangular-angle 0)
(analysis:candela-rectangular-color 0)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-profile #f)
(analysis:candela-rectangular-log-plot #f)
(analysis:candela-rectangular-max #f 0)
(analysis:candela-rectangular-min #f 0)
(analysis:candela-rectangular-contour #f)
(analysis:candela-rectangular-smooth #f 90)
(analysis:candela-rectangular-3d-plot #f)
(analysis:candela-rectangular-levels -1)
(analysis:candela-distribution 1 #f 500 #t #f)
(analysis:candela-distribution-luminaire 180)
(analysis:candela-distribution-max #f 0)
(analysis:candela-distribution-min #f 0)
(analysis:candela-distribution-log-plot #f)
(analysis:candela-rect-distribution-angular-width 180)
))

(define Macro1
   (lambda ( )
    (view:zoom-by-factor 0.90909090909091)
(view:zoom-by-factor 0.90909090909091)
(view:profiles "xy")
(view:zoom-all)
(edit:clear-selection)
(edit:add-selection (entity 25))
(edit:clear-selection)
(edit:add-selection (entity 53))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 0 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 1 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 2 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 1 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 0 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 1 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 0 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 3 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 5 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 4 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 3 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 0 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 1 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 2 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 4 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 3 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 2 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 1 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 2 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 3 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 4 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 3 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 1 (entity 53)))
(property:apply-surface (tools:face-in-body 1 (entity 53)) (list "Perfect Absorber" "Default")
  (gvector 0 0 0) (gvector 0 0 0)
  (position 0 0 0) (gvector 0 0 0) #t)
(property:apply-surface (tools:face-in-body 1 (entity 53)) (list "Perfect Absorber" "Default")
  (gvector 0 0 0) (gvector 0 0 0)
  (position 0 0 0) (gvector 0 0 0) #t)
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 3 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 0 (entity 53)))
(edit:clear-selection)
(edit:add-selection (tools:face-in-body 1 (entity 53)))
(edit:add-selection (tools:face-in-body 3 (entity 53)))
(property:apply-surface (tools:face-in-body 1 (entity 53)) (list "Perfect Absorber" "Default")
  (gvector 0 0 0) (gvector 0 0 0)
  (position 0 0 0) (gvector 0 0 0) #t)
(property:apply-surface (tools:face-in-body 3 (entity 53)) (list "Perfect Absorber" "Default")
  (gvector 0 0 0) (gvector 0 0 0)
  (position 0 0 0) (gvector 0 0 0) #t)
))

(define Macro1
   (lambda ( )
    (edit:clear-selection)
(edit:add-selection (tools:face-in-body 1 (entity 53)))
(edit:add-selection (tools:face-in-body 3 (entity 53)))
(property:apply-surface (tools:face-in-body 1 (entity 53)) (list "Perfect Absorber" "Default")
  (gvector 0 0 0) (gvector 0 0 0)
  (position 0 0 0) (gvector 0 0 0) #t)
(property:apply-surface (tools:face-in-body 3 (entity 53)) (list "Perfect Absorber" "Default")
  (gvector 0 0 0) (gvector 0 0 0)
  (position 0 0 0) (gvector 0 0 0) #t)
))

(define Macro1
   (lambda ( )
    (edit:select-all-objects)
))

(define Macro1
   (lambda ( )
    (property:apply-material (entity 152) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 1) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 2) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 3) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 4) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 5) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 6) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 7) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 8) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 9) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 10) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 11) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 12) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 13) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 14) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 15) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 16) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 17) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 18) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 19) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 20) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 21) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 22) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 23) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 24) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 25) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 26) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 27) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 28) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 29) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 30) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 31) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 32) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 33) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 34) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 35) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 36) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 37) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 38) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 39) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 40) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 41) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 42) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 43) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 44) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 45) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 46) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 47) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 48) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 49) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 50) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 51) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 52) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 53) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 54) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 55) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 56) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 57) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 58) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 59) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 60) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 61) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 62) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 63) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 64) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 65) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 66) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 67) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 68) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 69) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 70) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 71) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 72) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 73) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 74) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 75) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 76) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 77) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 78) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 79) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 80) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 81) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 82) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 83) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 84) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 85) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 86) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 87) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 88) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 89) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 90) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 91) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 92) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 93) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 94) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 95) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 96) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 97) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 98) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 99) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 100) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 101) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 102) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 103) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 104) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 105) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 106) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 107) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 108) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 109) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 110) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 111) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 112) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 113) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 114) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 115) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 116) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 117) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 118) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 119) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 120) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 121) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 122) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 123) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 124) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 125) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 126) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 127) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 128) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 129) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 130) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 131) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 132) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 133) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 134) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 135) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 136) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 137) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 138) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 139) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 140) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 141) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 142) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 143) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 144) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 145) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 146) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 147) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 148) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 149) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 150) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 151) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 153) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 154) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 155) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 156) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 157) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 158) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 159) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 160) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 161) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 162) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 163) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 164) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 165) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 166) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 167) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 168) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 169) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 170) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 171) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 172) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 173) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 174) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 175) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 176) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 177) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 178) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 179) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 180) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 181) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 182) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 183) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 184) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 185) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 186) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 187) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 188) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 189) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 190) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 191) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 192) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 193) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 194) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 195) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 196) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 197) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 198) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 199) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 200) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 201) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 202) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 203) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 204) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 205) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 206) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 207) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 208) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 209) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 210) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 211) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 212) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 213) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 214) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 215) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 216) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 217) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 218) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 219) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 220) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 221) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 222) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 223) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 224) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 225) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 226) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 227) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 228) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 229) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 230) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 231) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 232) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 233) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 234) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 235) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 236) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 237) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 238) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 239) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 240) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 241) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 242) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 243) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 244) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 245) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 246) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 247) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 248) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 249) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 250) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 251) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 252) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 253) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 254) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 255) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 256) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 257) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 258) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 259) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 260) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 261) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 262) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 263) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 264) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 265) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 266) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 267) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 268) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 269) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 270) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 271) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 272) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 273) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 274) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 275) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 276) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 277) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 278) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 279) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 280) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 281) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 282) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 283) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 284) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 285) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 286) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 287) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 288) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 289) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 290) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 291) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 292) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 293) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 294) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 295) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 296) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 297) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 298) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 299) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 300) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 301) "SCHOTT" "BK7" (gvector 0 0 0))
(property:apply-material (entity 302) "SCHOTT" "BK7" (gvector 0 0 0))
))

(define Macro1
   (lambda ( )
    (property:apply-material (entity 152) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 1) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 2) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 3) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 4) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 5) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 6) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 7) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 8) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 9) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 10) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 11) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 12) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 13) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 14) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 15) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 16) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 17) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 18) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 19) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 20) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 21) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 22) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 23) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 24) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 25) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 26) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 27) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 28) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 29) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 30) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 31) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 32) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 33) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 34) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 35) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 36) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 37) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 38) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 39) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 40) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 41) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 42) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 43) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 44) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 45) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 46) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 47) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 48) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 49) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 50) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 51) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 52) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 53) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 54) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 55) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 56) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 57) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 58) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 59) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 60) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 61) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 62) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 63) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 64) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 65) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 66) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 67) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 68) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 69) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 70) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 71) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 72) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 73) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 74) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 75) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 76) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 77) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 78) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 79) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 80) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 81) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 82) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 83) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 84) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 85) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 86) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 87) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 88) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 89) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 90) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 91) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 92) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 93) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 94) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 95) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 96) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 97) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 98) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 99) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 100) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 101) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 102) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 103) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 104) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 105) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 106) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 107) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 108) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 109) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 110) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 111) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 112) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 113) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 114) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 115) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 116) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 117) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 118) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 119) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 120) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 121) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 122) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 123) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 124) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 125) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 126) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 127) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 128) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 129) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 130) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 131) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 132) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 133) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 134) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 135) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 136) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 137) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 138) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 139) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 140) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 141) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 142) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 143) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 144) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 145) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 146) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 147) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 148) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 149) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 150) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 151) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 153) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 154) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 155) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 156) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 157) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 158) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 159) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 160) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 161) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 162) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 163) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 164) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 165) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 166) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 167) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 168) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 169) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 170) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 171) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 172) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 173) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 174) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 175) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 176) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 177) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 178) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 179) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 180) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 181) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 182) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 183) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 184) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 185) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 186) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 187) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 188) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 189) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 190) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 191) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 192) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 193) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 194) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 195) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 196) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 197) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 198) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 199) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 200) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 201) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 202) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 203) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 204) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 205) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 206) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 207) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 208) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 209) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 210) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 211) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 212) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 213) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 214) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 215) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 216) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 217) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 218) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 219) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 220) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 221) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 222) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 223) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 224) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 225) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 226) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 227) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 228) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 229) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 230) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 231) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 232) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 233) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 234) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 235) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 236) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 237) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 238) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 239) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 240) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 241) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 242) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 243) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 244) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 245) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 246) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 247) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 248) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 249) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 250) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 251) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 252) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 253) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 254) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 255) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 256) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 257) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 258) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 259) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 260) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 261) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 262) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 263) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 264) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 265) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 266) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 267) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 268) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 269) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 270) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 271) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 272) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 273) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 274) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 275) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 276) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 277) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 278) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 279) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 280) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 281) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 282) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 283) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 284) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 285) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 286) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 287) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 288) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 289) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 290) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 291) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 292) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 293) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 294) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 295) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 296) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 297) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 298) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 299) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 300) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 301) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 302) "SCHOTT" "FK54" (gvector 0 0 0))
))

(define Macro1
   (lambda ( )
    (edit:select-all-objects)
(property:apply-material (entity 226) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 1) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 2) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 3) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 4) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 5) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 6) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 7) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 8) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 9) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 10) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 11) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 12) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 13) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 14) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 15) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 16) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 17) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 18) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 19) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 20) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 21) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 22) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 23) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 24) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 25) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 26) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 27) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 28) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 29) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 30) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 31) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 32) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 33) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 34) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 35) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 36) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 37) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 38) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 39) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 40) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 41) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 42) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 43) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 44) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 45) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 46) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 47) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 48) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 49) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 50) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 51) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 52) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 53) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 54) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 55) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 56) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 57) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 58) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 59) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 60) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 61) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 62) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 63) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 64) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 65) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 66) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 67) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 68) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 69) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 70) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 71) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 72) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 73) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 74) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 75) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 76) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 77) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 78) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 79) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 80) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 81) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 82) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 83) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 84) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 85) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 86) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 87) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 88) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 89) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 90) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 91) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 92) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 93) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 94) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 95) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 96) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 97) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 98) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 99) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 100) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 101) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 102) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 103) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 104) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 105) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 106) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 107) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 108) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 109) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 110) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 111) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 112) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 113) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 114) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 115) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 116) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 117) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 118) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 119) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 120) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 121) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 122) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 123) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 124) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 125) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 126) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 127) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 128) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 129) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 130) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 131) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 132) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 133) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 134) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 135) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 136) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 137) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 138) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 139) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 140) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 141) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 142) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 143) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 144) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 145) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 146) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 147) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 148) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 149) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 150) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 151) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 152) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 153) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 154) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 155) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 156) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 157) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 158) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 159) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 160) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 161) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 162) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 163) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 164) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 165) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 166) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 167) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 168) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 169) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 170) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 171) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 172) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 173) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 174) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 175) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 176) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 177) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 178) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 179) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 180) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 181) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 182) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 183) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 184) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 185) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 186) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 187) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 188) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 189) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 190) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 191) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 192) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 193) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 194) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 195) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 196) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 197) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 198) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 199) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 200) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 201) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 202) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 203) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 204) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 205) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 206) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 207) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 208) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 209) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 210) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 211) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 212) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 213) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 214) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 215) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 216) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 217) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 218) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 219) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 220) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 221) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 222) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 223) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 224) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 225) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 227) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 228) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 229) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 230) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 231) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 232) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 233) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 234) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 235) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 236) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 237) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 238) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 239) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 240) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 241) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 242) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 243) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 244) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 245) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 246) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 247) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 248) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 249) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 250) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 251) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 252) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 253) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 254) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 255) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 256) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 257) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 258) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 259) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 260) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 261) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 262) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 263) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 264) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 265) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 266) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 267) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 268) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 269) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 270) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 271) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 272) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 273) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 274) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 275) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 276) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 277) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 278) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 279) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 280) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 281) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 282) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 283) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 284) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 285) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 286) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 287) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 288) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 289) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 290) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 291) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 292) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 293) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 294) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 295) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 296) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 297) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 298) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 299) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 300) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 301) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 302) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 303) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 304) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 305) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 306) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 307) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 308) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 309) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 310) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 311) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 312) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 313) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 314) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 315) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 316) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 317) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 318) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 319) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 320) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 321) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 322) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 323) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 324) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 325) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 326) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 327) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 328) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 329) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 330) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 331) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 332) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 333) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 334) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 335) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 336) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 337) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 338) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 339) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 340) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 341) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 342) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 343) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 344) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 345) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 346) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 347) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 348) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 349) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 350) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 351) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 352) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 353) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 354) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 355) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 356) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 357) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 358) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 359) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 360) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 361) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 362) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 363) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 364) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 365) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 366) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 367) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 368) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 369) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 370) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 371) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 372) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 373) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 374) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 375) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 376) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 377) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 378) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 379) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 380) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 381) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 382) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 383) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 384) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 385) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 386) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 387) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 388) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 389) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 390) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 391) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 392) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 393) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 394) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 395) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 396) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 397) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 398) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 399) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 400) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 401) "SCHOTT" "FK54" (gvector 0 0 0))
(property:apply-material (entity 402) "SCHOTT" "FK54" (gvector 0 0 0))
))

(define Macro1
   (lambda ( )
    (raytrace:set-importance-sampling-on)
(raytrace:set-polarization-off)
(raytrace:set-specular-rays-only-off)
(raytrace:set-aperture-diffraction-off)
(raytrace:set-ray-splitting-on)
(raytrace:set-random-rays 1)
(raytrace:set-aperture-diffraction-distance 1000000)
(raytrace:set-radiometric-units-photometric)
(raytrace:set-random-seed 1)
))